apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indower-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: indower-test-app
    networking.gke.io/managed-certificates: indowerappgooglemanagedcertificate
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: indower-app
      port:
        number: 80
